services:
  # db:
  #   container_name: ${MONGO_DB_NAME}    
  #   image: mongo:6.0
  #   volumes:
  #       - poke-vol:/data/db
  #   ports:
  #      - 27017:27017
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  #   command: ['--auth']

  # mongo-express:
  #   # depends_on:
  #   #   - db
  #   image: mongo-express:1.0.0-alpha.4
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
  #     ME_CONFIG_MONGODB_SERVER: ${DB_NAME}
  #   ports:
  #     - 8081:8081
  #   restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: 141102/parcial2:1.0
    # depesnds_on:
    #   - db
    ports:
      - 8080:8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - media-data:/data/media

volumes:
  poke-vol:
  media-data: