name: Deploy JAR app to Azure Web App - clinicapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'clinicapp'
          slot-name: 'Production'
          package: './target/gestionhistoriaclinica-0.0.1-SNAPSHOT.jar' # Update this path if necessary
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4699728D5D8A497794E366D981FBB21A }}
